vagrant:
  box: ubuntu/bionic64
  user: vagrant
  gui: false
  memory: 2048
  vcpus: 1
  vagrant_plugins:
    - name: vagrant-vbguest
    - name: vagrant-hostsupdater

firewall:
  enabled: true
  allowed_tcp_ports:
    - "21"
    - "22"
    - "25"
    - "80"
    - "443"
    - "3306"
    - "4444"
    - "8025"
    - "8080"
    - "8443"
    - "8983"
    - "9200"
  log_dropped_packets: false
  disable: true
  disable_ufw: true


  # Force use of ansible_local provisioner, even if Ansible is installed on host.
  force_ansible_local: false
